package me.zhang.generic;

import org.junit.Test;

/**
 * Created by zhangxiangdong on 2017/4/25.
 */
public class PairTest {

    @Test
    public void createPairArray() {
        Pair<Integer, String>[] pairs;

        // Generic types do not contain the type parameter at runtime. The type parameter is not used in creation.
        // There is no difference in the code generated by
        // new ArrayList<SomeType>() or new ArrayList<String>() or new ArrayList() at all.
        // http://docs.oracle.com/javase/tutorial/java/generics/erasure.html

        // pairs = new Pair<Integer, String>[3];
        pairs = new Pair[3];
        pairs[0] = new Pair<>(1, "HL");

        Pair<Integer, String> pair = pairs[0];
        System.out.println(pair.getKey() + ": " + pair.getValue());
    }

}